site_name: R in Production
site_url: https://rinprod.com
repo_url: https://github.com/rinprod/rinprod.com
docs_dir: content
site_dir: docs
theme:
  name: material
  logo: images/rinprod_r_small.png
  favicon: images/rinprod_r_small.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Overview: index.md
  - Learn:
    - learn/index.md 
    - Development Environments: learn/dev-envs.md
    - Publishing: learn/publishing.md
    - Unattended Code Execution: learn/code-exec.md
    - Packages: learn/packages.md
  - Resources: 
    - Writing production R code: writing-production-r.md
    - Other resources: resources.md
  - About: about.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 3
      permalink: true

plugins:
  - blog:
      post_url_format: "{slug}"
  - privacy
  - search
